### ISSUE TITLE
wx.env.USER_DATA_PATH

### ISSUE THREAD

**Issue by bp0002** [pony13500815917/rose#11]
wx.env.USER_DATA_PATH
这个保存文件时要用到的环境变量，官方文档里居然没有说明，仅在文件系统的说明的一段现在运行起来会报错的代码里出现 :(
https://developers.weixin.qq.com/minigame/dev/guide/base-ability/file-system.html

**Comment by bp0002** [comment]
// 添加一个 ?
declare namespace wx {
    type ENV = {
        USER_DATA_PATH: string;
    }

    var env: ENV;
}

**Comment by pony13500815917** [comment]
感谢反馈，已修复了。
