### ISSUE TITLE
function "createUserInfoButton" error

### ISSUE THREAD

**Issue by crawt** [pony13500815917/rose#12]
Fixed:
<pre> 
    /** 创建用户信息按钮*/
    function createUserInfoButton(object: {
        type: "text" | "image",
        text?: string,
        image?: string,
        style: {
            left: number,
            top: number,
            width: number,
            height: number,
            color?: string
            backgroundColor?: string,
            borderColor?: string,
            borderWidth?: number,
            borderRadius?: number,
            textAlign?: "left" | "center" | "right",
            fontSize?: number,
            lineHeight?: number
        },
        withCredentials?: boolean,
        lang?: "en" | "zh_CN" | "zh_TW"
    }): UserInfoButton;
</pre>

**Comment by pony13500815917** [comment]
感谢反馈，已修复了。
